config/routes.rb
SampleApp::Application.routes.draw do
  resources :slots

  resources :listings

  resources :clubs

  resources :sports

  resources :users do
    member do
      get :following, :followers
    end
  end

  get '/slotshow' , to: "users#slotshow"

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :slotposts, only: [:create, :destroy]

   
  root 'static_pages#home'
  match '/slotsharing', to:    'static_pages#slotsharing',    via: 'get'
  match '/microblog', to:    'static_pages#microblog',    via: 'get'
  match '/help', to:    'static_pages#help',    via: 'get'
  match '/about',to:    'static_pages#about',   via: 'get'
  match '/contact',to:  'static_pages#contact', via: 'get' 
  match '/signup',to:   'users#new',            via: 'get'
   match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete' 

end

app/models/slot.rb
class Slot < ActiveRecord::Base
	belongs_to :listing
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy]

  # GET /slots
  # GET /slots.json
  def index
    @slots = Slot.all
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
  end

  # GET /slots/new
  def new
    @slot = Slot.new
    @listings= Listing.all
    @sports= Sport.all
    @clubs= Club.all
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots
  # POST /slots.json
  def create
    @slot = Slot.new(slot_params)

    respond_to do |format|
      if @slot.save
        format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
        format.json { render action: 'show', status: :created, location: @slot }
      else
        format.html { render action: 'new' }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1
  # PATCH/PUT /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slot_params
      params.require(:slot).permit(:date, :start_time, :end_time, :slot_status, :listing_id)
    end
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_form.html.erb
<%= form_for(@slot) do |f| %>
  <% if @slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
      <% @slot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :slot_status %><br>
    <%= f.check_box :slot_status %>
  </div>
  <div class="field">
    <%= f.label :listing_id %><br>
    <%= f.collection_select :listing_id, Listing.all, :id, :id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Editing slot</h1>

<%= render 'form' %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<h1>Listing slots</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Slot status</th>
      <th>Listing</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <td><%= slot.date %></td>
        <td><%= slot.start_time %></td>
        <td><%= slot.end_time %></td>
        <td><%= slot.slot_status %></td>
        <td><%= slot.listing_id %></td>
        <td><%= link_to 'Show', slot %></td>
        <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
        <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slot', new_slot_path %>

app/views/slots/new.html.erb
<h1>New slot</h1>

<%= render 'form' %>

<%= link_to 'Back', slots_path %>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @slot.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @slot.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @slot.end_time %>
</p>

<p>
  <strong>Slot status:</strong>
  <%= @slot.slot_status %>
</p>

<p>
  <strong>Listing:</strong>
  <%= @slot.listing_id %>
</p>

<%= link_to 'Edit', edit_slot_path(@slot) %> |
<%= link_to 'Back', slots_path %>