config/routes.rb
SampleApp::Application.routes.draw do
  resources :slots

  resources :listings

  resources :clubs

  resources :sports

  resources :users do
    member do
      get :following, :followers
    end
  end

  get '/slotshow' , to: "users#slotshow"

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :slotposts, only: [:create, :destroy]

   
  root 'static_pages#home'
  match '/slotsharing', to:    'static_pages#slotsharing',    via: 'get'
  match '/microblog', to:    'static_pages#microblog',    via: 'get'
  match '/help', to:    'static_pages#help',    via: 'get'
  match '/about',to:    'static_pages#about',   via: 'get'
  match '/contact',to:  'static_pages#contact', via: 'get' 
  match '/signup',to:   'users#new',            via: 'get'
   match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete' 

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :club
	belongs_to :sport
	has_many :slots
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @q= Listing.ransack(params[:q])
    @listings = @q.result.includes(:club,:sport)
    
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @clubs= Club.all
  end

  # GET /listings/new
  def new
    @listing = Listing.new
    @sports = Sport.all
    @clubs= Club.all
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:club_id, :sport_id)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :club_id %><br>
    <%= f.collection_select :club_id, @clubs, :id, :club%>
  </div>
  <div class="field">
    <%= f.label :sport_id %><br>
    <%= f.collection_select :sport_id, @sports, :id, :sport%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Display Grounds</title>
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet"  />
  </head>

  <body>
    <div id="nav_bar">
      <p>
        <%= link_to "Home", root_path, class: "homepage" %>
        > Grounds in 
        
        

      </p>
    </div>
    <div class="form-inline">
      <%= search_form_for @q do |f| %>
      <div class="form-group">
        <%= f.label :club_city_cont, "City: ", { :class => 'control-label'} %>
        <div class="input">
          <%= f.collection_select :club_city_cont,  Club.select(:city).distinct, :city, :city, {:include_blank => 'None'} %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :sport_sport_cont, "Sport: ",  { :class => 'control-label'} %>
        <div class="input">
          <%= f.collection_select :sport_sport_cont, Sport.select(:sport).distinct, :sport, :sport, {:include_blank => 'None'} %>
        </div>
      </div>
      <div class="form-group"> 
      <%= f.submit class: 'btn btn-default' %>
      </div>
    <% end %>
    </div>
    
    <div id="Heading">
      Grounds in
    </div>

    <div class="container">
    <% @listings.each do |listing| %>
    <div class="row">
    <div class="col-md-12">
    <div class="col-sm-6 col-md-7">
      <div id="display_grounds">
      <ul>
        <li id="ground_name"><strong><a href="">
          <%= link_to listing.club.club, clubs_path(@club) %>
        </a></strong></li>
        <li id="address">Location : <%= listing.club.location %></li>
        <li id="phone">Contact : <%= listing.club.phone %></li>
        <li id="mail">Email : <%= listing.club.email %></li>
        <li id="sport">Sports Available : <%= listing.club.sports.pluck(:sport).flatten.join(", ")%> </li>
        <li>
          <div class="btn-group" role="group" aria-label="...">
            <button type="button" class="btn btn-default btn-sm">
            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></button>
            <button type="button" class="btn btn-default btn-sm">
            <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span></button>
            <button type="button" class="btn btn-default btn-sm">
            <span class="glyphicon glyphicon-heart" aria-hidden="true"></span></button>
          </div>
          <button type="button" class="btn btn-default">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Reviews</button>
        </li>
      </ul>
               
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div id="myCarousel" class="carousel slide" data-interval="5000">
        <ol class="carousel-indicators middle">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
          <div class="item active">
            <img src="assets/stadium1.jpeg" />
          </div>
          <div class="item">
            <img src="assets/stadium_cri1.jpeg" />
          </div>
          <div class="item">
            <img src="assets/stadium_hoc1.jpeg" />
          </div>
        </div>

        <!-- Controls -->
        <a class="carousel-control left" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="carousel-control right" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>

        </a>

      </div>
    </div>


    </div>
    </div>
    <% end %>
    </div>
    
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


<script type="text/javascript">
    $(document).ready(function(){
        $('.carousel').carousel()
    });
</script>
</body>
</html>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Club:</strong>
  <%= @listing.club_id %>
</p>

<p>
  <strong>Sport:</strong>
  <%= @listing.sport_id %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>